import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@radix-ui/themes/styles.css';
import "./globals.css";
import { Theme } from '@radix-ui/themes';
import 'regenerator-runtime/runtime'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <Theme
            accentColor="mint"
            grayColor="gray"
            panelBackground="solid"
            scaling="100%"
          >
              {children}
            <footer className="fixed bottom-0 w-full h-12 flex items-center justify-center border-t bg-white">
                <p className="text-center text-xs text-gray-400">
                  This voice assistant demo is for <a className="underline" href="https://aaltovai.wordpress.com/">course</a> study purposes only. All rights reserved by the developer.
                </p>
            </footer>
          </Theme>
      </body>
    </html>
  );
}
